name: Release from Master on Push

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HUSKY: 0

jobs:
  commit-lint:
    name: Commit Lint
    uses: ./.github/workflows/commit-lint-reusable.yml
    secrets: inherit

  code-style:
    name: Code Style
    uses: ./.github/workflows/code-style-reusable.yml
    secrets: inherit

  test:
    name: Run tests and report coverage
    uses: ./.github/workflows/test-reusable.yml
    secrets: inherit

  release:
    name: Build and release npm package
    needs: [commit-lint, code-style, test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Cache Dependencies
        uses: ./.github/actions/setup-node

      - name: Build
        run: npm run build

      - name: Release npm package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

